<dl>
    <dt>坪數</dt>
    <dd>
        <p>
            <label><input type="radio" name="bathroomQuestion01" value="1" /><span>1 坪以下</span></label>
            <label><input type="radio" name="bathroomQuestion01" value="2" /><span>1 ~ 1.3 坪</span></label>
            <label><input type="radio" name="bathroomQuestion01" value="3" /><span>1.3 ~ 1.5 坪</span></label>
            <label><input type="radio" name="bathroomQuestion01" value="4" /><span>1.5 坪以上</span></label>
        </p>
    </dd>
    <dt>馬桶</dt>
    <dd>
        <p>
            <label><input type="radio" name="bathroomQuestion02" value="1" /><span>新製 - 一般馬桶</span></label>
            <label><input type="radio" name="bathroomQuestion02" value="2" /><span>新製 - 免治馬桶</span></label>
            <label><input type="radio" name="bathroomQuestion02" value="3" /><span>不需更換</span></label>
            <label><input type="radio" name="bathroomQuestion02" value="4" /><span>未決定</span></label>
        </p>
    </dd>
    <dt>面盆</dt>
    <dd>
        <p>
            <label><input type="radio" name="bathroomQuestion03" value="1" /><span>新製 - 長柱</span></label>
            <label><input type="radio" name="bathroomQuestion03" value="2" /><span>新製  -短柱</span></label>
            <label><input type="radio" name="bathroomQuestion03" value="3" /><span>新製 - 單孔</span></label>
            <label><input type="radio" name="bathroomQuestion03" value="4" /><span>不需更換</span></label>
            <label><input type="radio" name="bathroomQuestion03" value="5" /><span>未決定</span></label>
        </p>
    </dd>
</dl>
