<dl>
    <dt>坪數</dt>
    <dd>
        <p>
            <?php echo $this->actionController->buildOptionString(
                    $this->decorationMap['bathroomQuestion01'],
                    $this->decorationRow['bathroomQuestion01']); ?>
        </p>
    </dd>
    <dt>馬桶</dt>
    <dd>
        <p>
            <?php echo $this->actionController->buildOptionString(
                    $this->decorationMap['bathroomQuestion02'],
                    $this->decorationRow['bathroomQuestion02']); ?>
        </p>
    </dd>
    <dt>面盆</dt>
    <dd>
        <p>
            <?php echo $this->actionController->buildOptionString(
                    $this->decorationMap['bathroomQuestion03'],
                    $this->decorationRow['bathroomQuestion03']); ?>
        </p>
    </dd>
</dl>
