<dl>
    <dt>裝修內容</dt>
    <dd>
        <p>
            <label><input type="checkbox" name="kitchenQuestion01" value="y" /><span>吊櫃</span></label>
            <label><input type="checkbox" name="kitchenQuestion02" value="y" /><span>下櫃</span></label>
        </p>
    </dd>
    <dt>設備是否保留</dt>
    <dd>
        <p>
            <label><input type="checkbox" name="kitchenQuestion03" value="y" /><span>瓦斯爐</span></label>
            <label><input type="checkbox" name="kitchenQuestion04" value="y" /><span>排油煙機</span></label>
        </p>
    </dd>
    <dt>現有廚具</dt>
    <dd>
        <p>
            <label><input type="radio" name="kitchenQuestion05" value="1" /><span>無（需新製）</span></label>
            <label><input type="radio" name="kitchenQuestion05" value="2" /><span>泥作</span></label>
            <label><input type="radio" name="kitchenQuestion05" value="3" /><span>組合式（分件廚具）</span></label>
            <label><input type="radio" name="kitchenQuestion05" value="4" /><span>歐化（木質桶身）</span></label>
            <label><input type="radio" name="kitchenQuestion05" value="5" /><span>不鏽鋼桶身</span></label>
        </p>
    </dd>
</dl>
